name: foodlyft
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  image_picker: ^0.6.7+17
  provider: ^4.3.2+4
  sliding_up_panel: ^1.0.2
  smooth_star_rating: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/failed.png
    - assets/images/sucess.png
    - assets/images/cash.png
    - assets/images/visa.png
    - assets/images/mastercard.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/twitter.png
    - assets/images/user.png
    - assets/images/password.png
    - assets/images/eye.png
    - assets/images/fastfood.jpg
    - assets/images/western.jpg
    - assets/images/arab.jpg
    - assets/images/italian.jpg
    - assets/images/drinks.jpg
    - assets/images/breakfast.jpg
    - assets/images/bilad.png
    - assets/images/Hayfa.png
    - assets/images/hadrmawt.png
    - assets/images/halab.jpg
    - assets/images/Mac.png
    - assets/images/pizza.png
    - assets/images/kfc.png
    - assets/images/carls.png
    - assets/images/burger-1.png
    - assets/images/burger-2.png
    - assets/images/delete.png
    - assets/images/pizza1.png
    - assets/images/pastry.png
    - assets/images/drink.png
    - assets/images/veg.png
    - assets/images/foodlyft_logo_splash.png
    - assets/images/start_background.jpg
    - assets/images/knife_spoon_fork.png
    - assets/images/logo_foodlyft.png
    - assets/images/name.png
    - assets/images/phone.png

    # - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # roboto & quicksand
    # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Black.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BlackItalic.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BoldItalic.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Italic.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplaySC-Black.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplaySC-BlackItalic.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplaySC-Bold.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplaySC-BoldItalic.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplaySC-Italic.otf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplaySC-Regular.otf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Semibold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Semibolditalic.ttf

    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans-BoldItalic.ttf
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
        - asset: assets/fonts/JosefinSans/JosefinSans-Italic.ttf
        - asset: assets/fonts/JosefinSans/JosefinSans-Light.ttf
        - asset: assets/fonts/JosefinSans/JosefinSans-LightItalic.ttf
        - asset: assets/fonts/JosefinSans/JosefinSans-Regular.ttf    
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBold.ttf    
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBoldItalic.ttf    
        - asset: assets/fonts/JosefinSans/JosefinSans-Thin.ttf    
        - asset: assets/fonts/JosefinSans/JosefinSans-ThinItalic.ttf    

  # fonts:
  #   - family: Trajan Pro
  #   fonts:
  #     - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #       weight: 700
  #  - family: Roboto
  #    fonts:
  #     - asset: assets/fonts/Roboto-Regular.ttf
  #  - family: Poppins
  #    fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #  - family: Poppins-medium
  #    fonts:
  #     - asset: assets/fonts/Poppins-Medium.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
