export 'package:flutter/material.dart';
export '../../../../services/general/hexColor.dart';
export '../widgets/footer.dart';
export '../widgets/mainText.dart';
export '../widgets/paymentInfo.dart';
export '../widgets/customerInfo.dart';
export '../widgets/image.dart';
export '../../../../providers/restaurants.provider.dart';
export 'package:provider/provider.dart';